# Generated by Django 4.2.2 on 2025-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="has_elec_heating",
            field=models.BooleanField(
                default=None, null=True, verbose_name="has electric heating"
            ),
        ),
        migrations.AddField(
            model_name="consumption",
            name="has_anomaly",
            field=models.BooleanField(
                default=None, null=True, verbose_name="has anomaly"
            ),
        ),
    ]
