# Generated by Django 4.2.2 on 2025-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_auto_20250921_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="has_recent_anomaly",
            field=models.BooleanField(
                default=None, null=True, verbose_name="has anomaly"
            ),
        ),
    ]
